from google.cloud import bigquery

BQ_TABLE_SCHEMA = [
    bigquery.SchemaField("id",                  bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("conversation_id",     bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("created_at",          bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("date",                bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("timezone",            bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("place",               bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("tweet",               bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("language",            bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("hashtags",            bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("cashtags",            bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("user_id",             bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("user_id_str",         bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("username",            bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("name",                bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("day",                 bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("hour",                bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("link",                bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("urls",                bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("photos",              bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("video",               bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("thumbnail",           bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("retweet",             bigquery.enums.SqlTypeNames.BOOLEAN),
    bigquery.SchemaField("nlikes",              bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("nreplies",            bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("nretweets",           bigquery.enums.SqlTypeNames.INT64),
    bigquery.SchemaField("quote_url",           bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("search",              bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("near",                bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("geo",                 bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("source",              bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("user_rt_id",          bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("user_rt",             bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("retweet_id",          bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("reply_to",            bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("retweet_date",        bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("translate",           bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("trans_src",           bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("trans_dest",          bigquery.enums.SqlTypeNames.STRING),
    bigquery.SchemaField("champion",            bigquery.enums.SqlTypeNames.STRING)
]
