@echo off

SET GCP_PROJECT_NAME=rock-sentinel
SET FUNCTIONS_REGION=us-east1

SET BQ_DATASET_RAW_NAME=raw
SET BQ_DATASET_MASTER_NAME=master
SET BQ_DATASET_APPLICATION_NAME=application

SET GS_MASTER_DATA_BUCKET_NAME=sentiment_master_data

SET BQ_TABLE_RAW_TWEETS_DATA_NAME=tweets_data
SET BQ_TABLE_MASTER_TWEETS_DATA_NAME=tweets_data
SET BQ_TABLE_MASTER_TWEETS_DATA_SCHEMA=bigquery\schemas\master_tweet_data.json
SET BQ_QUERY_TWEETS_DATA_MASTERIZATION=bigquery\queries\dist\masterize_tweet_data.sql

SET BQ_TABLE_MASTER_TWEETS_SENTIMENT_NAME=tweets_sentiment
SET BQ_TABLE_MASTER_TWEETS_SENTIMENT_SCHEMA=bigquery\schemas\master_tweet_sentiment.json

SET BQ_VIEW_MASTER_TWEETS_PENDING_SENTIMENT_NAME=v_tweets_data_pending_sentiment
SET BQ_VIEW_MASTER_TWEETS_PENDING_SENTIMENT_QUERY=bigquery\queries\dist\v_tweets_pending_sentiment.sql

SET BQ_VIEW_MASTER_SENTIMENT_APPLICATION_DATA_NAME=v_sentiment_enriched
SET BQ_VIEW_MASTER_SENTIMENT_APPLICATION_DATA_QUERY=bigquery\queries\dist\v_sentiment_enriched.sql